name: CLI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: ./create-onchain
        run: bun install

      - name: Build CLI
        working-directory: ./create-onchain
        run: bun run build

      - name: Make CLI executable
        run: chmod +x ./create-onchain/dist/esm/cli.js

      - name: Run CLI with automated responses
        run: |
          yes "" | head -n 4 | ./create-onchain/dist/esm/cli.js

      # - name: List directories
      #   run: ls -la test-project

      - name: Install & Build test project
        working-directory: ./my-onchainkit-app
        run: |
          bun install
          bun run build
